ext {
    rustore_billingclient_version = '10.5.0'
    sdk_version_code = 100500

    destination_project = '../ru.rustore.billing'

    sdk_billingclient_dependency = "ru.rustore.sdk:billingclient:$rustore_billingclient_version"
    kotlin_version = '2.2.21'
    sdk_kotlin_jdk_version = kotlin_version
    sdk_kotlin_jdk_dependency = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$sdk_kotlin_jdk_version"
    sdk_maven_repos = 'https://artifactory-external.vkpartner.ru/artifactory/maven-rustore-exposed'
}
buildscript {
    ext.kotlin_version = '2.2.21'
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            url = uri(sdk_maven_repos)
        }
    }
}

tasks.register('clean', Delete) {
    delete rootProject.layout.buildDirectory
}
